//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LicenseManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;RSAKeyValue&gt;&lt;Modulus&gt;wSphdbZAHIJ6vYVjqkZPA2g7Y58P1Iw299pYGkqkY8j91/vLwBQnyvTENgj/PkrsaQcCVyM8SLX/IwInH0XCeFuM4JQscLD98fskLwqq1QB7CqcFKntAPG7VQ46HcL596jjIYyXLk/ZKCu4DKkDxtDeAkrdrShsdErFc+oI7xL8=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;P&gt;6g69p2DtxiMtsVu79dkx5uf977gLMw1ueZetdwd53DHz0jy2Dvu9V5iRVX9bHs15lWBs6eup4esp7Q4szLLx8w==&lt;/P&gt;&lt;Q&gt;00ZAp5MtgEObXgiQJKwhV7ob0t/GuR9RxqBIyZSrlo2acf1v+/EogWIMOZ5iFdIWtXSCut/WbRCumA+I8jaJBQ==&lt;/Q&gt;&lt;DP&gt;YgjOkx7cONNfPhxIPA8/AZJGIHQb7MRBc5h+RY7SEdKyZ2qabug [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string privatekey {
            get {
                return ResourceManager.GetString("privatekey", resourceCulture);
            }
        }
    }
}
